name: pr-lint-be

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"

jobs:
  Lint-Frontend:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v3
        working-directory: backend
        with:
          path: frontend
          node-version: "14.21.2"
          cache: "npm"

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Get changed files by action
        id: changed-files
        uses: tj-actions/changed-files@v20
        with:
          path: backend
          files: |
            backend/**/*.ts

      - name: List all changed files (ACMR) https://github.com/tj-actions/changed-files#outputs
        run: |
          cd             backend
          CHANGED_FILES=$(echo "${{ steps.changed-files.outputs.added_files }} ${{ steps.changed-files.outputs.modified_files }}" | xargs -n1 | sed "s/^backend\///" | xargs)
          npm run lint $CHANGED_FILES
